services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gguip-github-io-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/private:/app/src/private
    env_file:
      - .env